/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS 側 DeviceInfo。`sourceKind` は文字列（"mic"|"system"|"process"）。 */
export interface JsDeviceInfo {
  id: string
  name: string
  sourceKind: string
  sampleRate: number
  channels: number
  isLoopback: boolean
  isDefault: boolean
}
/**
 * JS 側 AudioChunk。`data` は interleaved f32（len = frames * channels）。
 * `seq`(u64) は精度欠落を避けて BigInt。`flags` は ChunkFlags のビット(u32)。
 */
export interface JsAudioChunk {
  data: Float32Array
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  peak: number
  rms: number
}
/** JS 側ストリームイベント。`type` で種別、`count`/`message` は任意。 */
export interface JsStreamEvent {
  type: string
  count?: number
  message?: string
}
/** JS 側デバイスイベント。`type` で種別、device/id/sourceKind は任意。 */
export interface JsDeviceEvent {
  type: string
  device?: JsDeviceInfo
  id?: string
  sourceKind?: string
}
/** openStream / __openMockStream のオプション。 */
export interface OpenOptions {
  /** "mic" | "system" | "process" | "mix" */
  kind: string
  deviceId?: string
  processId?: number
  /**
   * process の対象 PID の扱い（process 専用）。"include"（既定）| "exclude"。
   * include=対象 PID だけ録る / exclude=対象 PID 以外の全システム音（process_id 必須）。
   * mic / system では無視。Linux / Windows / macOS の 3 OS とも対応。
   */
  mode?: string
  /**
   * システム音から自ホスト（自プロセス）の音を除くか（system 専用。mix では
   * system 側に適用）。既定 false。mic / process では無視。
   * Linux / Windows / macOS の 3 OS とも対応。
   */
  excludeSelf?: boolean
  /** 既定 48000 */
  outputRate?: number
  /** 既定 2 */
  outputChannels?: number
  /** 既定 20 */
  chunkMs?: number
  /**
   * 開始時の入力ゲイン（線形倍率）。既定 1.0。1.0=そのまま、2.0=約+6dB、0.0=無音。
   * 実行時変更は `setGain`。
   */
  gain?: number
  /** mix の mic 側で選ぶ入力デバイス ID（mix 専用）。未指定なら既定入力。 */
  micDeviceId?: string
  /** mix の system 側で選ぶ出力エンドポイント ID（mix 専用）。未指定なら既定出力。 */
  systemDeviceId?: string
  /** mix の mic 側の合成前倍率（線形・mix 専用）。既定 1.0。合成後に `gain` が掛かる。 */
  micGain?: number
  /** mix の system 側の合成前倍率（線形・mix 専用）。既定 1.0。 */
  systemGain?: number
}
/** 利用可能なデバイスを列挙する。ヘッドレス環境では空配列でも throw しない。 */
export declare function devices(): NapiResult
/** ストリームを開いて開始し、チャンク/イベントをコールバックへ送る `FlexStream` を返す。 */
export declare function openStream(options: OpenOptions, onChunk: ChunkTsfn, onEvent?: EventTsfn | undefined | null): NapiResult
/** デバイス着脱を監視し、イベントをコールバックへ送る `DeviceWatcherHandle` を返す。 */
export declare function watchDevices(onEvent: DeviceTsfn): NapiResult
/**
 * テスト専用・公開 API 外。
 *
 * 低レベル `Stream::open` に `MockBackend` を渡してストリームを作り、`open_stream` と
 * 同じ bridge / TSFN 経路で回す。実音なしで marshaling 全経路（Float32Array・BigInt・
 * peak/rms・frames）を end-to-end 検証する。本番コードからは使わないこと。
 *
 * JS 名は `__openMockStream`。先頭 `__` で公開 API 外を示す。napi の既定変換は先頭
 * アンダースコアを落として `openMockStream` にしてしまうので `js_name` で固定する。
 */
export declare function __openMockStream(sampleRate: number, channels: number, freqHz: number, onChunk: ChunkTsfn): NapiResult
/**
 * 録音ストリームのハンドル。内部で bridge スレッドが `flexaudio::Stream` を
 * 所有・ポーリングし、チャンク/イベントを TSFN 経由で JS へ送る。
 */
export class FlexStream {
  /** 録音を停止し bridge スレッドを join する。二重呼び出し安全。 */
  stop(): void
  /**
   * 録音を止めずに入力ソース（mic/system/process）をホットスワップする。
   *
   * `options` から構築した `StreamConfig` への切替を bridge スレッドへ依頼し、結果を
   * 同期的に返す（成功で `Ok`、失敗で例外）。出力フォーマット（`outputRate`/
   * `outputChannels`）は切替では変えられない（連続ストリームの frames が変わるため）。
   * 変更を要求すると `switch_source` が InvalidArg を返し、ここで例外になる。切替前後で
   * チャンクの `seq` は連続し、切替後最初のチャンクには DISCONTINUITY フラグが立つ。
   * `options.gain` は無視される（ゲインはストリームの状態。変更は `setGain`）。
   *
   * 既に `stop()` 済み（bridge スレッド停止後）なら例外を返す。
   */
  switchSource(options: OpenOptions): NapiResult
  /**
   * 録音を一時停止する。デバイスは動かしたまま配信だけ止める。`resume` で再開し、
   * 再開後の最初のチャンクに DISCONTINUITY が立つ。既に `stop()` 済みなら例外。
   */
  pause(): NapiResult
  /** 一時停止を解除して配信を再開する。既に `stop()` 済みなら例外。 */
  resume(): NapiResult
  /**
   * 入力ゲイン（線形倍率）を変更する。1.0=そのまま、2.0=約+6dB、0.0=無音。録音中
   * いつでも呼べて、次のチャンクから効く（20ms 粒度）。乗算後のサンプルは ±1.0 に
   * クランプされる。有限かつ 0 以上でなければ例外。既に `stop()` 済みなら例外。
   */
  setGain(gain: number): NapiResult
}
/** デバイス着脱監視のハンドル。bridge スレッドが `DeviceWatcher` を poll する。 */
export class DeviceWatcherHandle {
  /** 監視を停止し bridge スレッドを join する。二重呼び出し安全。 */
  stop(): void
}
